p8105_hw2_yc3577
================
Yimeng Cai
10/01/2023

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.1     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(dplyr)
library(readxl)
```

Problem 1

Step 1 clean & analyze pols-month data using read_csv to read the data,
then use separate function to separate the mon variable into day year
month. Then rename the month int data into month names. Finally use
mutate to take values of gop and dem into president. Then select related
columns and drop na.

``` r
pols_df = 
  read_csv("fivethirtyeight_datasets/pols-month.csv") |>
  separate(mon, into = c('year', 'month', 'day'), sep = '-') 
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
month_names = 
  c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
pols_df$month = month_names[as.integer(pols_df$month)]
pols_df = 
  mutate( pols_df,
    president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop"),
    year = as.integer(year)) |>
  select(-day, -starts_with("prez")) |>
  drop_na()
pols_df
```

    ## # A tibble: 822 × 9
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 Jan        23      51     253      23      45     198 dem      
    ##  2  1947 Feb        23      51     253      23      45     198 dem      
    ##  3  1947 Mar        23      51     253      23      45     198 dem      
    ##  4  1947 Apr        23      51     253      23      45     198 dem      
    ##  5  1947 May        23      51     253      23      45     198 dem      
    ##  6  1947 Jun        23      51     253      23      45     198 dem      
    ##  7  1947 Jul        23      51     253      23      45     198 dem      
    ##  8  1947 Aug        23      51     253      23      45     198 dem      
    ##  9  1947 Sep        23      51     253      23      45     198 dem      
    ## 10  1947 Oct        23      51     253      23      45     198 dem      
    ## # ℹ 812 more rows

Step 2 clean & analyze snp data using read_csv to read the data, then
use separate function to separate the mon variable into day year month.
Then formulate the variable type of month day and year. Use relocate to
arrange the column in the orders of year and month. Then select related
columns and drop na.

``` r
snp_df = 
  read_csv("fivethirtyeight_datasets/snp.csv") |>
  separate(date, into = c('month', 'day', 'year'), sep = '/') |>
  mutate(
    month = as.integer(month),
    day = as.integer(day),
    year = as.integer(year),
    month = month(month, label = TRUE),
    year = ifelse(year<16, year+2000, year+1900)) |>
  relocate(year, month) |>
  select(year, month, close) |>
  drop_na()
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp_df
```

    ## # A tibble: 787 × 3
    ##     year month close
    ##    <dbl> <ord> <dbl>
    ##  1  2015 Jul   2080.
    ##  2  2015 Jun   2063.
    ##  3  2015 May   2107.
    ##  4  2015 Apr   2086.
    ##  5  2015 Mar   2068.
    ##  6  2015 Feb   2104.
    ##  7  2015 Jan   1995.
    ##  8  2014 Dec   2059.
    ##  9  2014 Nov   2068.
    ## 10  2014 Oct   2018.
    ## # ℹ 777 more rows

Step 3 clean & analyze unemployment data using read_csv to read the
data, then use separate function to separate the mon variable into day
year month. Then formulate the variable type of month day and year. Use
relocate to arrange the column in the orders of year and month. Then
select related columns and drop na.

``` r
unem_df =  
  read_csv("fivethirtyeight_datasets/unemployment.csv") |>
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment"
  )|>
  mutate(
    year = as.integer(year))|>
  select(year, month, unemployment) |>
  drop_na()
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unem_df
```

    ## # A tibble: 810 × 3
    ##     year month unemployment
    ##    <int> <chr>        <dbl>
    ##  1  1948 Jan            3.4
    ##  2  1948 Feb            3.8
    ##  3  1948 Mar            4  
    ##  4  1948 Apr            3.9
    ##  5  1948 May            3.5
    ##  6  1948 Jun            3.6
    ##  7  1948 Jul            3.6
    ##  8  1948 Aug            3.9
    ##  9  1948 Sep            3.8
    ## 10  1948 Oct            3.7
    ## # ℹ 800 more rows

``` r
combined_df1 =
  left_join(pols_df, snp_df)|>
  left_join(x = _, y = unem_df)
```

    ## Joining with `by = join_by(year, month)`
    ## Joining with `by = join_by(year, month)`

``` r
combined_df1
```

    ## # A tibble: 822 × 11
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1947 Jan        23      51     253      23      45     198 dem          NA
    ##  2  1947 Feb        23      51     253      23      45     198 dem          NA
    ##  3  1947 Mar        23      51     253      23      45     198 dem          NA
    ##  4  1947 Apr        23      51     253      23      45     198 dem          NA
    ##  5  1947 May        23      51     253      23      45     198 dem          NA
    ##  6  1947 Jun        23      51     253      23      45     198 dem          NA
    ##  7  1947 Jul        23      51     253      23      45     198 dem          NA
    ##  8  1947 Aug        23      51     253      23      45     198 dem          NA
    ##  9  1947 Sep        23      51     253      23      45     198 dem          NA
    ## 10  1947 Oct        23      51     253      23      45     198 dem          NA
    ## # ℹ 812 more rows
    ## # ℹ 1 more variable: unemployment <dbl>

Problem 2

Step 1 Clean and read Mytrash data using `read_excel` and `clean_names`.
Then use `mutate` to calculate homes_powered by inputting the function
`(weight_tons*500)/30`. Use `add_column(type = "Mytrash")` to add
additional variable to dataset for later combining usage. Finally drop
NA data in dumpster with `drop_na(starts_with("dumpster"))`.

``` r
Mrtrash_df = 
  read_excel("202309 Trash Wheel Collection Data.xlsx", sheet = 1, range = "A2:N587") |>
  janitor::clean_names() |>
  mutate(
    homes_powered = (weight_tons*500)/30) |>
  add_column(type = "Mrtrash")|>
  drop_na(starts_with("dumpster"))
Mrtrash_df
```

    ## # A tibble: 584 × 15
    ##    dumpster month year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ##  2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ##  3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ##  4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ##  5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ##  6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ##  7        7 May   2014  2014-05-21 00:00:00        1.91                  8
    ##  8        8 May   2014  2014-05-28 00:00:00        3.7                  16
    ##  9        9 June  2014  2014-06-05 00:00:00        2.52                 14
    ## 10       10 June  2014  2014-06-11 00:00:00        3.76                 18
    ## # ℹ 574 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>, type <chr>

``` r
sum(Mrtrash_df['weight_tons'])
```

    ## [1] 1875.1

Step 2 Clean and read Proftrash data using `read_excel` and
`clean_names`. Then use `mutate` to calculate homes_powered by inputting
the function `(weight_tons*500)/30`. Then formulate the year column into
character with `as.character(year)`. Use
`add_column(type = "Proftrash")` to add additional variable to dataset
for later combining usage. Finally drop NA data in dumpster with
`drop_na(starts_with("dumpster"))`.

``` r
Proftrash_df = 
  read_excel("202309 Trash Wheel Collection Data.xlsx", sheet = 2) |>
  janitor::clean_names() |>
  mutate(
    homes_powered = (weight_tons*500)/30,
    year = as.character(year))|>
  add_column(type = "Proftrash")|>
  drop_na(starts_with("dumpster"))

Proftrash_df
```

    ## # A tibble: 106 × 14
    ##    dumpster month    year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 January  2017  2017-01-02 00:00:00        1.79                 15
    ##  2        2 January  2017  2017-01-30 00:00:00        1.58                 15
    ##  3        3 February 2017  2017-02-26 00:00:00        2.32                 18
    ##  4        4 February 2017  2017-02-26 00:00:00        3.72                 15
    ##  5        5 February 2017  2017-02-28 00:00:00        1.45                 15
    ##  6        6 March    2017  2017-03-30 00:00:00        1.71                 15
    ##  7        7 April    2017  2017-04-01 00:00:00        1.82                 15
    ##  8        8 April    2017  2017-04-20 00:00:00        2.37                 15
    ##  9        9 May      2017  2017-05-10 00:00:00        2.64                 15
    ## 10       10 May      2017  2017-05-26 00:00:00        2.78                 15
    ## # ℹ 96 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, type <chr>

``` r
sum(Proftrash_df['weight_tons'])
```

    ## [1] 216.26

Step 3 Clean and read Gwytrash data using `read_excel` and
`clean_names`. Then use `mutate` to calculate homes_powered by inputting
the function `(weight_tons*500)/30`. Then formulate the year column into
character with `as.character(year)`. Use `add_column(type = "Gwytrash")`
to add additional variable to dataset for later combining usage. Finally
drop NA data in dumpster with `drop_na(starts_with("dumpster"))`.

``` r
Gwytrash_df = 
  read_excel("202309 Trash Wheel Collection Data.xlsx", sheet = 4) |>
  janitor::clean_names() |>
  mutate(
    homes_powered = (weight_tons*500)/30,
    year = as.character(year))|>
  add_column(type = "Gwytrash")|>
  drop_na(starts_with("dumpster"))

Gwytrash_df
```

    ## # A tibble: 155 × 13
    ##    dumpster month  year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 July   2021  2021-07-03 00:00:00        0.93                 15
    ##  2        2 July   2021  2021-07-07 00:00:00        2.26                 15
    ##  3        3 July   2021  2021-07-07 00:00:00        1.62                 15
    ##  4        4 July   2021  2021-07-16 00:00:00        1.76                 15
    ##  5        5 July   2021  2021-07-30 00:00:00        1.53                 15
    ##  6        6 August 2021  2021-08-11 00:00:00        2.06                 15
    ##  7        7 August 2021  2021-08-14 00:00:00        1.9                  15
    ##  8        8 August 2021  2021-08-16 00:00:00        2.16                 15
    ##  9        9 August 2021  2021-08-16 00:00:00        2.6                  15
    ## 10       10 August 2021  2021-08-17 00:00:00        3.21                 15
    ## # ℹ 145 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, type <chr>

``` r
sum(Gwytrash_df['weight_tons'])
```

    ## [1] 451.65

Step 4 Combine `Mytrash_df`, `Proftrash_df` using 1st `bind_rows`. Then
combine binded dataframe with `Gwytrash_df` using 2nd `bind_rows`.

``` r
combine_df2 = 
  bind_rows(Mrtrash_df, Proftrash_df) |>
  bind_rows(x = _, y = Gwytrash_df)

combine_df2
```

    ## # A tibble: 845 × 15
    ##    dumpster month year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ##  2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ##  3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ##  4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ##  5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ##  6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ##  7        7 May   2014  2014-05-21 00:00:00        1.91                  8
    ##  8        8 May   2014  2014-05-28 00:00:00        3.7                  16
    ##  9        9 June  2014  2014-06-05 00:00:00        2.52                 14
    ## 10       10 June  2014  2014-06-11 00:00:00        3.76                 18
    ## # ℹ 835 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>, type <chr>

``` r
summary(Mrtrash_df)
```

    ##     dumpster        month               year          
    ##  Min.   :  1.0   Length:584         Length:584        
    ##  1st Qu.:146.8   Class :character   Class :character  
    ##  Median :292.5   Mode  :character   Mode  :character  
    ##  Mean   :292.5                                        
    ##  3rd Qu.:438.2                                        
    ##  Max.   :584.0                                        
    ##       date                         weight_tons    volume_cubic_yards
    ##  Min.   :1900-01-20 00:00:00.00   Min.   :0.780   Min.   : 7.0      
    ##  1st Qu.:2016-07-28 18:00:00.00   1st Qu.:2.720   1st Qu.:15.0      
    ##  Median :2018-09-01 00:00:00.00   Median :3.195   Median :15.0      
    ##  Mean   :2018-07-23 03:36:59.18   Mean   :3.211   Mean   :15.3      
    ##  3rd Qu.:2020-11-17 12:00:00.00   3rd Qu.:3.730   3rd Qu.:15.0      
    ##  Max.   :2023-06-29 00:00:00.00   Max.   :5.620   Max.   :20.0      
    ##  plastic_bottles  polystyrene   cigarette_butts  glass_bottles   
    ##  Min.   : 210    Min.   :  48   Min.   :   900   Min.   :  0.00  
    ##  1st Qu.:1000    1st Qu.: 555   1st Qu.:  3900   1st Qu.: 10.00  
    ##  Median :1900    Median :1160   Median :  6500   Median : 18.00  
    ##  Mean   :1979    Mean   :1558   Mean   : 19833   Mean   : 21.62  
    ##  3rd Qu.:2780    3rd Qu.:2400   3rd Qu.: 24000   3rd Qu.: 30.00  
    ##  Max.   :5960    Max.   :6540   Max.   :310000   Max.   :110.00  
    ##   plastic_bags       wrappers     sports_balls   homes_powered  
    ##  Min.   :  24.0   Min.   : 180   Min.   : 0.00   Min.   :13.00  
    ##  1st Qu.: 290.0   1st Qu.: 750   1st Qu.: 6.00   1st Qu.:45.33  
    ##  Median : 635.0   Median :1100   Median :11.00   Median :53.25  
    ##  Mean   : 916.8   Mean   :1416   Mean   :13.17   Mean   :53.51  
    ##  3rd Qu.:1242.0   3rd Qu.:1980   3rd Qu.:18.25   3rd Qu.:62.17  
    ##  Max.   :3750.0   Max.   :5085   Max.   :56.00   Max.   :93.67  
    ##      type          
    ##  Length:584        
    ##  Class :character  
    ##  Mode  :character  
    ##                    
    ##                    
    ## 

``` r
var(Mrtrash_df)
```

    ## Warning in var(Mrtrash_df): NAs introduced by coercion

    ##                         dumpster month          year date   weight_tons
    ## dumpster            2.847000e+04    NA  4.259425e+02   NA   -6.22524871
    ## month                         NA    NA            NA   NA            NA
    ## year                4.259425e+02    NA  6.476770e+00   NA   -0.08008394
    ## date                          NA    NA            NA   NA            NA
    ## weight_tons        -6.225249e+00    NA -8.008394e-02   NA    0.56307691
    ## volume_cubic_yards -4.778045e+01    NA -7.118177e-01   NA    0.26539099
    ## plastic_bottles     5.574203e+03    NA  7.864120e+01   NA  -49.60949547
    ## polystyrene        -1.421168e+05    NA -2.132730e+03   NA  -40.31636340
    ## cigarette_butts    -3.355355e+06    NA -5.144545e+04   NA 2233.85492023
    ## glass_bottles      -1.293611e+03    NA -2.017389e+01   NA    0.45405232
    ## plastic_bags       -8.058486e+04    NA -1.205685e+03   NA   13.76221587
    ## wrappers           -7.461537e+04    NA -1.111248e+03   NA   11.09104743
    ## sports_balls        1.755168e+02    NA  2.476138e+00   NA    0.13213853
    ## homes_powered      -1.037542e+02    NA -1.334733e+00   NA    9.38461525
    ## type                          NA    NA            NA   NA            NA
    ##                    volume_cubic_yards plastic_bottles   polystyrene
    ## dumpster                  -47.7804460       5574.2033 -1.421168e+05
    ## month                              NA              NA            NA
    ## year                       -0.7118177         78.6412 -2.132730e+03
    ## date                               NA              NA            NA
    ## weight_tons                 0.2653910        -49.6095 -4.031636e+01
    ## volume_cubic_yards          1.8458963        197.7213  4.599063e+02
    ## plastic_bottles           197.7213104    1124386.3648  6.566353e+05
    ## polystyrene               459.9062713     656635.2896  1.514496e+06
    ## cigarette_butts          8272.2694377    6923203.0361  1.945807e+07
    ## glass_bottles               5.2628645       7031.8660  1.010008e+04
    ## plastic_bags              357.7741136     333164.3902  7.669829e+05
    ## wrappers                  345.0616497     448553.5504  8.037091e+05
    ## sports_balls                0.7190853       5750.4319  2.703983e+03
    ## homes_powered               4.4231832       -826.8251 -6.719395e+02
    ## type                               NA              NA            NA
    ##                    cigarette_butts glass_bottles  plastic_bags      wrappers
    ## dumpster              -3355355.197 -1.293611e+03  -80584.86449 -7.461537e+04
    ## month                           NA            NA            NA            NA
    ## year                    -51445.451 -2.017389e+01   -1205.68488 -1.111248e+03
    ## date                            NA            NA            NA            NA
    ## weight_tons               2233.855  4.540523e-01      13.76222  1.109105e+01
    ## volume_cubic_yards        8272.269  5.262864e+00     357.77411  3.450616e+02
    ## plastic_bottles        6923203.036  7.031866e+03  333164.39023  4.485536e+05
    ## polystyrene           19458069.579  1.010008e+04  766982.94422  8.037091e+05
    ## cigarette_butts      872814136.445  3.395874e+05 8937490.19679  1.038471e+07
    ## glass_bottles           339587.414  2.575795e+02    6034.84348  7.345425e+03
    ## plastic_bags           8937490.197  6.034843e+03  703943.55999  6.776041e+05
    ## wrappers              10384706.994  7.345425e+03  677604.14627  8.142563e+05
    ## sports_balls             19331.241  5.533160e+01    2242.35242  2.919717e+03
    ## homes_powered            37230.921  7.567540e+00     229.37018  1.848507e+02
    ## type                            NA            NA            NA            NA
    ##                    sports_balls homes_powered type
    ## dumpster           1.755168e+02   -103.754163   NA
    ## month                        NA            NA   NA
    ## year               2.476138e+00     -1.334733   NA
    ## date                         NA            NA   NA
    ## weight_tons        1.321385e-01      9.384615   NA
    ## volume_cubic_yards 7.190853e-01      4.423183   NA
    ## plastic_bottles    5.750432e+03   -826.825062   NA
    ## polystyrene        2.703983e+03   -671.939461   NA
    ## cigarette_butts    1.933124e+04  37230.920580   NA
    ## glass_bottles      5.533160e+01      7.567540   NA
    ## plastic_bags       2.242352e+03    229.370179   NA
    ## wrappers           2.919717e+03    184.850682   NA
    ## sports_balls       9.138825e+01      2.202309   NA
    ## homes_powered      2.202309e+00    156.410256   NA
    ## type                         NA            NA   NA

``` r
summary(Proftrash_df)
```

    ##     dumpster         month               year          
    ##  Min.   :  1.00   Length:106         Length:106        
    ##  1st Qu.: 27.25   Class :character   Class :character  
    ##  Median : 53.50   Mode  :character   Mode  :character  
    ##  Mean   : 53.50                                        
    ##  3rd Qu.: 79.75                                        
    ##  Max.   :106.00                                        
    ##                                                        
    ##       date                         weight_tons    volume_cubic_yards
    ##  Min.   :2017-01-02 00:00:00.00   Min.   :0.610   Min.   : 6.00     
    ##  1st Qu.:2018-05-31 18:00:00.00   1st Qu.:1.610   1st Qu.:15.00     
    ##  Median :2019-08-13 00:00:00.00   Median :1.975   Median :15.00     
    ##  Mean   :2019-12-12 16:31:41.89   Mean   :2.040   Mean   :14.58     
    ##  3rd Qu.:2021-07-29 00:00:00.00   3rd Qu.:2.487   3rd Qu.:15.00     
    ##  Max.   :2023-06-29 00:00:00.00   Max.   :3.720   Max.   :18.00     
    ##                                                                     
    ##  plastic_bottles  polystyrene    cigarette_butts glass_bottles  
    ##  Min.   : 657    Min.   :  180   Min.   : 3800   Min.   : 0.00  
    ##  1st Qu.:3800    1st Qu.:  980   1st Qu.: 6400   1st Qu.: 8.00  
    ##  Median :4900    Median : 3750   Median : 8800   Median :14.00  
    ##  Mean   :5244    Mean   : 4194   Mean   :11531   Mean   :16.81  
    ##  3rd Qu.:7200    3rd Qu.: 7650   3rd Qu.:15000   3rd Qu.:24.00  
    ##  Max.   :9830    Max.   :11528   Max.   :33320   Max.   :48.00  
    ##  NA's   :1       NA's   :1       NA's   :1       NA's   :1      
    ##   plastic_bags      wrappers     homes_powered       type          
    ##  Min.   :  140   Min.   : 2300   Min.   :10.17   Length:106        
    ##  1st Qu.:  720   1st Qu.: 4400   1st Qu.:26.83   Class :character  
    ##  Median : 1040   Median : 5800   Median :32.92   Mode  :character  
    ##  Mean   : 2433   Mean   : 7695   Mean   :34.00                     
    ##  3rd Qu.: 1870   3rd Qu.: 9800   3rd Qu.:41.46                     
    ##  Max.   :13450   Max.   :20100   Max.   :62.00                     
    ##  NA's   :1       NA's   :1

``` r
var(Proftrash_df)
```

    ## Warning in var(Proftrash_df): NAs introduced by coercion

    ##                        dumpster month        year date weight_tons
    ## dumpster           945.16666667    NA 56.54761905   NA   4.0552381
    ## month                        NA    NA          NA   NA          NA
    ## year                56.54761905    NA  3.50916442   NA   0.2425750
    ## date                         NA    NA          NA   NA          NA
    ## weight_tons          4.05523810    NA  0.24257502   NA   0.4306571
    ## volume_cubic_yards  -0.03809524    NA -0.03647799   NA   0.3139838
    ## plastic_bottles              NA    NA          NA   NA          NA
    ## polystyrene                  NA    NA          NA   NA          NA
    ## cigarette_butts              NA    NA          NA   NA          NA
    ## glass_bottles                NA    NA          NA   NA          NA
    ## plastic_bags                 NA    NA          NA   NA          NA
    ## wrappers                     NA    NA          NA   NA          NA
    ## homes_powered       67.58730929    NA  4.04291747   NA   7.1776184
    ## type                         NA    NA          NA   NA          NA
    ##                    volume_cubic_yards plastic_bottles polystyrene
    ## dumpster                  -0.03809524              NA          NA
    ## month                              NA              NA          NA
    ## year                      -0.03647799              NA          NA
    ## date                               NA              NA          NA
    ## weight_tons                0.31398383              NA          NA
    ## volume_cubic_yards         2.58796047              NA          NA
    ## plastic_bottles                    NA              NA          NA
    ## polystyrene                        NA              NA          NA
    ## cigarette_butts                    NA              NA          NA
    ## glass_bottles                      NA              NA          NA
    ## plastic_bags                       NA              NA          NA
    ## wrappers                           NA              NA          NA
    ## homes_powered              5.23306392              NA          NA
    ## type                               NA              NA          NA
    ##                    cigarette_butts glass_bottles plastic_bags wrappers
    ## dumpster                        NA            NA           NA       NA
    ## month                           NA            NA           NA       NA
    ## year                            NA            NA           NA       NA
    ## date                            NA            NA           NA       NA
    ## weight_tons                     NA            NA           NA       NA
    ## volume_cubic_yards              NA            NA           NA       NA
    ## plastic_bottles                 NA            NA           NA       NA
    ## polystyrene                     NA            NA           NA       NA
    ## cigarette_butts                 NA            NA           NA       NA
    ## glass_bottles                   NA            NA           NA       NA
    ## plastic_bags                    NA            NA           NA       NA
    ## wrappers                        NA            NA           NA       NA
    ## homes_powered                   NA            NA           NA       NA
    ## type                            NA            NA           NA       NA
    ##                    homes_powered type
    ## dumpster               67.587309   NA
    ## month                         NA   NA
    ## year                    4.042917   NA
    ## date                          NA   NA
    ## weight_tons             7.177618   NA
    ## volume_cubic_yards      5.233064   NA
    ## plastic_bottles               NA   NA
    ## polystyrene                   NA   NA
    ## cigarette_butts               NA   NA
    ## glass_bottles                 NA   NA
    ## plastic_bags                  NA   NA
    ## wrappers                      NA   NA
    ## homes_powered         119.626973   NA
    ## type                          NA   NA

``` r
summary(Gwytrash_df)
```

    ##     dumpster         month               year          
    ##  Min.   :  1.00   Length:155         Length:155        
    ##  1st Qu.: 38.50   Class :character   Class :character  
    ##  Median : 77.00   Mode  :character   Mode  :character  
    ##  Mean   : 77.14                                        
    ##  3rd Qu.:115.50                                        
    ##  Max.   :154.00                                        
    ##                                                        
    ##       date                         weight_tons    volume_cubic_yards
    ##  Min.   :2021-07-03 00:00:00.00   Min.   :0.770   Min.   : 5.0      
    ##  1st Qu.:2021-11-03 12:00:00.00   1st Qu.:2.585   1st Qu.:15.0      
    ##  Median :2022-06-10 00:00:00.00   Median :3.000   Median :15.0      
    ##  Mean   :2022-05-20 20:44:54.19   Mean   :2.914   Mean   :14.9      
    ##  3rd Qu.:2022-10-11 12:00:00.00   3rd Qu.:3.335   3rd Qu.:15.0      
    ##  Max.   :2023-06-30 00:00:00.00   Max.   :4.180   Max.   :15.0      
    ##                                                                     
    ##  plastic_bottles  polystyrene    cigarette_butts  plastic_bags   
    ##  Min.   :   0    Min.   :  0.0   Min.   :   0    Min.   :   0.0  
    ##  1st Qu.: 640    1st Qu.: 77.5   1st Qu.:1150    1st Qu.: 190.0  
    ##  Median :1200    Median :180.0   Median :2200    Median : 360.0  
    ##  Mean   :1495    Mean   :170.7   Mean   :2368    Mean   : 788.8  
    ##  3rd Qu.:2100    3rd Qu.:240.0   3rd Qu.:3350    3rd Qu.:1200.0  
    ##  Max.   :5400    Max.   :540.0   Max.   :6400    Max.   :3600.0  
    ##                                                                  
    ##     wrappers    homes_powered       type          
    ##  Min.   : 540   Min.   :12.83   Length:155        
    ##  1st Qu.:1000   1st Qu.:43.08   Class :character  
    ##  Median :1400   Median :50.00   Mode  :character  
    ##  Mean   :1554   Mean   :48.56                     
    ##  3rd Qu.:2075   3rd Qu.:55.58                     
    ##  Max.   :3500   Max.   :69.67                     
    ##  NA's   :117

``` r
var(Gwytrash_df)
```

    ## Warning in var(Gwytrash_df): NAs introduced by coercion

    ##                         dumpster month          year date   weight_tons
    ## dumpster             1996.845161    NA  2.588827e+01   NA  3.874797e+00
    ## month                         NA    NA            NA   NA            NA
    ## year                   25.888270    NA  4.217009e-01   NA -5.529954e-03
    ## date                          NA    NA            NA   NA            NA
    ## weight_tons             3.874797    NA -5.529954e-03   NA  3.926719e-01
    ## volume_cubic_yards      0.793297    NA -1.876833e-02   NA  2.050126e-01
    ## plastic_bottles     14062.402933    NA  2.610342e+02   NA -2.195287e+02
    ## polystyrene           -62.423544    NA  8.415375e+00   NA -2.343939e+01
    ## cigarette_butts      6583.480938    NA  2.032375e+02   NA -3.693752e+02
    ## plastic_bags       -18168.029409    NA -1.809088e+02   NA -2.064870e+02
    ## wrappers                      NA    NA            NA   NA            NA
    ## homes_powered          64.579954    NA -9.216580e-02   NA  6.544532e+00
    ## type                          NA    NA            NA   NA            NA
    ##                    volume_cubic_yards plastic_bottles   polystyrene
    ## dumpster                   0.79329703     14062.40293    -62.423544
    ## month                              NA              NA            NA
    ## year                      -0.01876833       261.03419      8.415375
    ## date                               NA              NA            NA
    ## weight_tons                0.20501257      -219.52875    -23.439393
    ## volume_cubic_yards         0.80745706        26.10859      5.265186
    ## plastic_bottles           26.10858819   1185508.69275 103946.157520
    ## polystyrene                5.26518643    103946.15752  13407.297863
    ## cigarette_butts           71.97989108   1294640.74906 129475.586510
    ## plastic_bags              30.91294512    333992.65253  52384.339966
    ## wrappers                           NA              NA            NA
    ## homes_powered              3.41687624     -3658.81197   -390.656542
    ## type                               NA              NA            NA
    ##                    cigarette_butts plastic_bags wrappers homes_powered type
    ## dumpster                6583.48094 -18168.02941       NA    64.5799545   NA
    ## month                           NA           NA       NA            NA   NA
    ## year                     203.23754   -180.90884       NA    -0.0921658   NA
    ## date                            NA           NA       NA            NA   NA
    ## weight_tons             -369.37522   -206.48696       NA     6.5445320   NA
    ## volume_cubic_yards        71.97989     30.91295       NA     3.4168762   NA
    ## plastic_bottles      1294640.74906 333992.65253       NA -3658.8119716   NA
    ## polystyrene           129475.58651  52384.33997       NA  -390.6565416   NA
    ## cigarette_butts      1914497.75450 688327.58190       NA -6156.2530964   NA
    ## plastic_bags          688327.58190 653708.79204       NA -3441.4492712   NA
    ## wrappers                        NA           NA       NA            NA   NA
    ## homes_powered          -6156.25310  -3441.44927       NA   109.0755314   NA
    ## type                            NA           NA       NA            NA   NA

Paragraphs about these data:

We get the basic information from `summary(Mrtrash_df)` MrTrash
dataframe has 584 ovbservations and 15 variables. The variables are
collection date, dumpster number, dumpster types, and total
litters.(e.g.dumpster, month, year, date, weight_tons,
volume_cubic_yards). We calculated the `home_powered`. The total weight
of trash collected by MRTrash is 1875.1 tons.

We get the basic information from `summary(Proftrash_df)` Proftrash
dataframe has 106 ovbservations and 14 variables. The variables are
collection date, dumpster number, dumpster types, and total
litters(e.g. dumpster, month, year, date, weight_tons,
volume_cubic_yards). We calculated the `home_powered`. The total weight
of trash collected by Proftrash is 216.26 tons.

We get the basic information from `summary(Gwytrash_df)` Gwytrash
dataframe has 155 ovbservations and 13 variables. The variables are
collection date, dumpster number, dumpster types, and total litters. We
calculated the `home_powered`. The total weight of trash collected by
Gwytrash is 451.65 tons.

Answers to the questions: 1. What was the total weight of trash
collected by Professor Trash Wheel?

The total weight of trash collected by Professor Trash Wheel is 216.26
tons.

2.  What was the total number of cigarette butts collected by Gwynnda in
    July of 2021?

The total number of cigarette butts collected by Gwynnda in July of 2021
is 1.63^4.

Problem 3

Step 1 Read and Clean the `MCI_baseline.csv` of baseline data using
`read_csv` and then use `janitor::clean_names()` to clean the variable
names. During table reading, we need to skip the 1st row with
`skip = 1`. Then we need to mutate the variable of sex and apoe4 with
`mutate(sex = recode( sex = recode(sex, "0" = "F", "1" = "M"), apoe4 = recode(apoe4, "0" = "apoe4_noncarrier", "1" = "apoe4_carrier")`
to make sure sex and apoe4 are appropriately encoded into character
format, and change the ‘.’ into ‘NA’ by
`age_at_onset = ifelse(age_at_onset == ".", NA, age_at_onset)` for later
fileter steps. Finally, we need to use filter of
`filter(current_age < age_at_onset | is.na(age_at_onset))` to remove any
participants who do not meet the stated inclusion criteria.

``` r
base_df = 
  read_csv("/Users/christinecym/Desktop/R data/P8105/HW/P8105_hw2_yc3577/data_mci/MCI_baseline.csv", skip =1) |>
  janitor::clean_names()|>
  mutate(
    sex = recode(sex, "0" = "F", "1" = "M"),
    apoe4 = recode(apoe4, "0" = "apoe4_noncarrier", "1" = "apoe4_carrier"),
    age_at_onset = ifelse(age_at_onset == ".", NA, age_at_onset)
    )|>
  filter(current_age < age_at_onset | is.na(age_at_onset))
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
base_df
```

    ## # A tibble: 479 × 6
    ##       id current_age sex   education apoe4            age_at_onset
    ##    <dbl>       <dbl> <chr>     <dbl> <chr>            <chr>       
    ##  1     1        63.1 F            16 apoe4_carrier    <NA>        
    ##  2     2        65.6 F            20 apoe4_carrier    <NA>        
    ##  3     3        62.5 M            16 apoe4_carrier    66.8        
    ##  4     4        69.8 F            16 apoe4_noncarrier <NA>        
    ##  5     5        66   M            16 apoe4_noncarrier 68.7        
    ##  6     6        62.5 M            16 apoe4_noncarrier <NA>        
    ##  7     7        66.5 M            18 apoe4_noncarrier 74          
    ##  8     8        67.2 F            18 apoe4_noncarrier <NA>        
    ##  9     9        66.7 F            16 apoe4_noncarrier <NA>        
    ## 10    10        64.1 F            18 apoe4_noncarrier <NA>        
    ## # ℹ 469 more rows

Step 2 Read and Clean the `mci_amyloid.csv` of biomarkers using
`read_csv` and then use `janitor::clean_names()` to clean the variable
names. During table reading, we need to skip the 1st row with
`skip = 1`. Then we need to rename the variable name with
`rename(id = ..., time_0 = ...)` to make sure we have a common name id,
and same format of time_X by change baseline to the time_0. Finally, we
need to use `pivot_longer(time0:time8, names_to = ..., values_to = ...)`
to make a tidy table with a column named `"period_time"` that includes
all the time_period into one column as a new variable. Then finally drop
na data with `drop_na()`.

``` r
amy_df = 
  read_csv("/Users/christinecym/Desktop/R data/P8105/HW/P8105_hw2_yc3577/data_mci/mci_amyloid.csv", skip =1) |>
  janitor::clean_names() |>
  rename(
    id = study_id,
    time_0 = baseline
  )|>
  pivot_longer(
    time_0:time_8,
    names_to = "period_time",
    values_to = "year") |>
  drop_na()
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
amy_df
```

    ## # A tibble: 2,272 × 3
    ##       id period_time year       
    ##    <dbl> <chr>       <chr>      
    ##  1     1 time_0      0.1105487  
    ##  2     1 time_4      0.109325197
    ##  3     1 time_6      0.104756131
    ##  4     1 time_8      0.107257697
    ##  5     2 time_0      0.107481183
    ##  6     2 time_2      0.109157373
    ##  7     2 time_4      0.109457839
    ##  8     2 time_6      0.105729713
    ##  9     2 time_8      0.10661845 
    ## 10     3 time_0      0.106087034
    ## # ℹ 2,262 more rows

Step 3 Combine two tables use `anti_join(base_df, amy_df)` based on the
common ID, since we need to find the only participants in each datasets.
We need to use anti_join twice to find each differences.
(`anti_join(amy_df, base_df)`). Then we need to use
`inner_join(base_df, amy_df)` base on the common ID to find the
participants in both datasets.

``` r
combine_df3 =
  anti_join(base_df, amy_df)
```

    ## Joining with `by = join_by(id)`

``` r
combine_df3
```

    ## # A tibble: 8 × 6
    ##      id current_age sex   education apoe4            age_at_onset
    ##   <dbl>       <dbl> <chr>     <dbl> <chr>            <chr>       
    ## 1    14        58.4 F            20 apoe4_noncarrier 66.2        
    ## 2    49        64.7 M            16 apoe4_noncarrier 68.4        
    ## 3    92        68.6 F            20 apoe4_noncarrier <NA>        
    ## 4   179        68.1 M            16 apoe4_noncarrier <NA>        
    ## 5   268        61.4 F            18 apoe4_carrier    67.5        
    ## 6   304        63.8 F            16 apoe4_noncarrier <NA>        
    ## 7   389        59.3 F            16 apoe4_noncarrier <NA>        
    ## 8   412        67   M            16 apoe4_carrier    <NA>

``` r
combine_df4 = 
  anti_join(amy_df, base_df)
```

    ## Joining with `by = join_by(id)`

``` r
combine_df4
```

    ## # A tibble: 76 × 3
    ##       id period_time year       
    ##    <dbl> <chr>       <chr>      
    ##  1    72 time_0      0.106965463
    ##  2    72 time_4      0.107266218
    ##  3    72 time_6      0.106665207
    ##  4   234 time_0      0.110521689
    ##  5   234 time_2      0.110988335
    ##  6   234 time_4      0.110318671
    ##  7   234 time_6      0.107334344
    ##  8   234 time_8      0.108868811
    ##  9   283 time_0      0.113436336
    ## 10   283 time_2      0.106568976
    ## # ℹ 66 more rows

``` r
combine_df5 =
  inner_join(base_df, amy_df)
```

    ## Joining with `by = join_by(id)`

``` r
combine_df5
```

    ## # A tibble: 2,196 × 8
    ##       id current_age sex   education apoe4        age_at_onset period_time year 
    ##    <dbl>       <dbl> <chr>     <dbl> <chr>        <chr>        <chr>       <chr>
    ##  1     1        63.1 F            16 apoe4_carri… <NA>         time_0      0.11…
    ##  2     1        63.1 F            16 apoe4_carri… <NA>         time_4      0.10…
    ##  3     1        63.1 F            16 apoe4_carri… <NA>         time_6      0.10…
    ##  4     1        63.1 F            16 apoe4_carri… <NA>         time_8      0.10…
    ##  5     2        65.6 F            20 apoe4_carri… <NA>         time_0      0.10…
    ##  6     2        65.6 F            20 apoe4_carri… <NA>         time_2      0.10…
    ##  7     2        65.6 F            20 apoe4_carri… <NA>         time_4      0.10…
    ##  8     2        65.6 F            20 apoe4_carri… <NA>         time_6      0.10…
    ##  9     2        65.6 F            20 apoe4_carri… <NA>         time_8      0.10…
    ## 10     3        62.5 M            16 apoe4_carri… 66.8         time_0      0.10…
    ## # ℹ 2,186 more rows

``` r
summary(base_df)
```

    ##        id         current_age        sex              education   
    ##  Min.   :  1.0   Min.   :56.00   Length:479         Min.   :12.0  
    ##  1st Qu.:121.5   1st Qu.:63.15   Class :character   1st Qu.:16.0  
    ##  Median :242.0   Median :64.90   Mode  :character   Median :16.0  
    ##  Mean   :242.0   Mean   :65.03                      Mean   :16.4  
    ##  3rd Qu.:362.5   3rd Qu.:67.00                      3rd Qu.:18.0  
    ##  Max.   :483.0   Max.   :72.90                      Max.   :20.0  
    ##     apoe4           age_at_onset      
    ##  Length:479         Length:479        
    ##  Class :character   Class :character  
    ##  Mode  :character   Mode  :character  
    ##                                       
    ##                                       
    ## 

``` r
var(base_df)
```

    ## Warning in var(base_df): NAs introduced by coercion

    ##                       id current_age sex  education apoe4 age_at_onset
    ## id           19540.06903  -20.945965  NA -18.032643    NA           NA
    ## current_age    -20.94597    8.732088  NA   0.143443    NA           NA
    ## sex                   NA          NA  NA         NA    NA           NA
    ## education      -18.03264    0.143443  NA   4.185428    NA           NA
    ## apoe4                 NA          NA  NA         NA    NA           NA
    ## age_at_onset          NA          NA  NA         NA    NA           NA

``` r
summary(amy_df)
```

    ##        id        period_time            year          
    ##  Min.   :  1.0   Length:2272        Length:2272       
    ##  1st Qu.:125.0   Class :character   Class :character  
    ##  Median :247.0   Mode  :character   Mode  :character  
    ##  Mean   :248.4                                        
    ##  3rd Qu.:371.2                                        
    ##  Max.   :495.0

``` r
var(amy_df)
```

    ## Warning in var(amy_df): NAs introduced by coercion

    ##                   id period_time year
    ## id          20403.61          NA   NA
    ## period_time       NA          NA   NA
    ## year              NA          NA   NA

``` r
calculation_df = base_df |>
  mutate(
    current_age = as.numeric(current_age),
    apoe4 = recode(apoe4, "apoe4_noncarrier" = 0, "apoe4_carrier" = 1)
  )
calculation_df
```

    ## # A tibble: 479 × 6
    ##       id current_age sex   education apoe4 age_at_onset
    ##    <dbl>       <dbl> <chr>     <dbl> <dbl> <chr>       
    ##  1     1        63.1 F            16     1 <NA>        
    ##  2     2        65.6 F            20     1 <NA>        
    ##  3     3        62.5 M            16     1 66.8        
    ##  4     4        69.8 F            16     0 <NA>        
    ##  5     5        66   M            16     0 68.7        
    ##  6     6        62.5 M            16     0 <NA>        
    ##  7     7        66.5 M            18     0 74          
    ##  8     8        67.2 F            18     0 <NA>        
    ##  9     9        66.7 F            16     0 <NA>        
    ## 10    10        64.1 F            18     0 <NA>        
    ## # ℹ 469 more rows

``` r
mean(calculation_df$current_age)
```

    ## [1] 65.0286

``` r
sum(calculation_df['apoe4'])
```

    ## [1] 144

``` r
sum(calculation_df['sex'] == 'F')
```

    ## [1] 210

``` r
sum(calculation_df['sex'] == 'M')
```

    ## [1] 269

``` r
sum(calculation_df['apoe4'] == '1')
```

    ## [1] 144

``` r
calc_df = calculation_df |>
  filter(sex =="F" & apoe4 == "1")
calc_df
```

    ## # A tibble: 63 × 6
    ##       id current_age sex   education apoe4 age_at_onset
    ##    <dbl>       <dbl> <chr>     <dbl> <dbl> <chr>       
    ##  1     1        63.1 F            16     1 <NA>        
    ##  2     2        65.6 F            20     1 <NA>        
    ##  3    22        67.3 F            20     1 74.6        
    ##  4    26        64.8 F            20     1 71.1        
    ##  5    34        64.8 F            16     1 <NA>        
    ##  6    39        68.3 F            16     1 70.2        
    ##  7    43        67.1 F            16     1 71.6        
    ##  8    47        66.1 F            12     1 <NA>        
    ##  9    50        67.6 F            18     1 <NA>        
    ## 10    52        63.2 F            16     1 <NA>        
    ## # ℹ 53 more rows

``` r
nrow(calc_df)
```

    ## [1] 63

Paragraphs about these data:

We get the basic information from `summary(base_df)` base_df dataframe
has 479 ovbservations and 6 variables, and it is the dataframe that
measures the basic demographic information of baseline samples. The
variables are like sex, educations years, APOE4 carrier or not,
current_age and the age with MCI onset. (e.g. id, current_age, sex,
education, apoe4, age_at_on_set).

We get the basic information from `summary(amy_df)` amy_df dataframe has
2272 ovbservations and 3 variables, and it is the dataframe that
measures the Time (in years) elapsed since the study baseline to the
visit where biomarker Amyloid 42/40 ratio was measured. The variables
are like id, period_time, year.

Answers to the questions: 1. How many participants were recruited, and
of those how many develop MCI?

483 participants were recruited, since there are 483 rows in the
original dataset of `MCI_baseline.csv`. Of those, 479 developed MCI.

2.  What is the average baseline age?

The average baseline age is 65.0286.

3.  What proportion of women in the study are APOE4 carriers?

P(APOE+ & women)/ P(women) = (63/479)/(210/479) = 0.3 = 30% The
proportion of women in the study are APOE4 carriers is 30%.
